 Завантажте вбудований датасет load_breast_cancer з бібліотеки
sklearn.datasets.

In [27]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [28]:
from google.colab import files
import pandas as pd
# Завантаження файлу
uploaded = files.upload()

df = pd.read_csv('breast_cancer.csv')
df

Saving breast_cancer.csv to breast_cancer.csv


569  \
17.99 10.38 122.80 1001.0 0.11840 0.27760 0.30010 0.14710 0.2419 0.07871 1.0950 0.9053 8.589 153.40 0.006399 0.04904 0.05373 0.01587 0.03003 0.006193 25.380 17.33 184.60 2019.0 0.16220 0.66560 0.7119  0.2654   
20.57 17.77 132.90 1326.0 0.08474 0.07864 0.08690 0.07017 0.1812 0.05667 0.5435 0.7339 3.398 74.08  0.005225 0.01308 0.01860 0.01340 0.01389 0.003532 24.990 23.41 158.80 1956.0 0.12380 0.18660 0.2416  0.1860   
19.69 21.25 130.00 1203.0 0.10960 0.15990 0.19740 0.12790 0.2069 0.05999 0.7456 0.7869 4.585 94.03  0.006150 0.04006 0.03832 0.02058 0.02250 0.004571 23.570 25.53 152.50 1709.0 0.14440 0.42450 0.4504  0.2430   
11.42 20.38 77.58  386.1  0.14250 0.28390 0.24140 0.10520 0.2597 0.09744 0.4956 1.1560 3.445 27.23  0.009110 0.07458 0.05661 0.01867 0.05963 0.009208 14.910 26.50 98.87  567.7  0.20980 0.86630 0.6869  0.2575   
20.29 14.34 135.10 1297.0 0.10030 0.13280 0.19800 0.10430 0.1809 0.05883 0.7572 0.7813 5.438 94.44  0.011490 0.02461 0.05688 0.01885 0.01756 0.005115 22.540 16.67 152.20 1575.0 0.13740 0.20500 0.4000  0.1625   
...                                                                                                                                                                                                         ...   
21.56 22.39 142.00 1479.0 0.11100 0.11590 0.24390 0.13890 0.1726 0.05623 1.1760 1.2560 7.673 158.70 0.010300 0.02891 0.05198 0.02454 0.01114 0.004239 25.450 26.40 166.10 2027.0 0.14100 0.21130 0.4107  0.2216   
20.13 28.25 131.20 1261.0 0.09780 0.10340 0.14400 0.09791 0.1752 0.05533 0.7655 2.4630 5.203 99.04  0.005769 0.02423 0.03950 0.01678 0.01898 0.002498 23.690 38.25 155.00 1731.0 0.11660 0.19220 0.3215  0.1628   
16.60 28.08 108.30 858.1  0.08455 0.10230 0.09251 0.05302 0.1590 0.05648 0.4564 1.0750 3.425 48.55  0.005903 0.03731 0.04730 0.01557 0.01318 0.003892 18.980 34.12 126.70 1124.0 0.11390 0.30940 0.3403  0.1418   
20.60 29.33 140.10 1265.0 0.11780 0.27700 0.35140 0.15200 0.2397 0.07016 0.7260 1.5950 5.772 86.22  0.006522 0.06158 0.07117 0.01664 0.02324 0.006185 25.740 39.42 184.60 1821.0 0.16500 0.86810 0.9387  0.2650   
7.76  24.54 47.92  181.0  0.05263 0.04362 0.00000 0.00000 0.1587 0.05884 0.3857 1.4280 2.548 19.15  0.007189 0.00466 0.00000 0.00000 0.02676 0.002783 9.456  30.37 59.16  268.6  0.08996 0.06444 0.0000  0.0000   

                                                                                                                                                                                                             30  \
17.99 10.38 122.80 1001.0 0.11840 0.27760 0.30010 0.14710 0.2419 0.07871 1.0950 0.9053 8.589 153.40 0.006399 0.04904 0.05373 0.01587 0.03003 0.006193 25.380 17.33 184.60 2019.0 0.16220 0.66560 0.7119  0.4601   
20.57 17.77 132.90 1326.0 0.08474 0.07864 0.08690 0.07017 0.1812 0.05667 0.5435 0.7339 3.398 74.08  0.005225 0.01308 0.01860 0.01340 0.01389 0.003532 24.990 23.41 158.80 1956.0 0.12380 0.18660 0.2416  0.2750   
19.69 21.25 130.00 1203.0 0.10960 0.15990 0.19740 0.12790 0.2069 0.05999 0.7456 0.7869 4.585 94.03  0.006150 0.04006 0.03832 0.02058 0.02250 0.004571 23.570 25.53 152.50 1709.0 0.14440 0.42450 0.4504  0.3613   
11.42 20.38 77.58  386.1  0.14250 0.28390 0.24140 0.10520 0.2597 0.09744 0.4956 1.1560 3.445 27.23  0.009110 0.07458 0.05661 0.01867 0.05963 0.009208 14.910 26.50 98.87  567.7  0.20980 0.86630 0.6869  0.6638   
20.29 14.34 135.10 1297.0 0.10030 0.13280 0.19800 0.10430 0.1809 0.05883 0.7572 0.7813 5.438 94.44  0.011490 0.02461 0.05688 0.01885 0.01756 0.005115 22.540 16.67 152.20 1575.0 0.13740 0.20500 0.4000  0.2364   
...                                                                                                                                                                                                         ...   
21.56 22.39 142.00 1479.0 0.11100 0.11590 0.24390 0.13890 0.1726 0.05623 1.1760 1.2560 7.673 158.70 0.010300 0.02891 0.05198 0.02454 0.01114 0.004239 25.450 26.40 166.10 2027.0 0.14100 0.21130 0

Проведіть попередній аналіз даних:
1. Перегляньте перші кілька рядків.
2. Перевірте назви стовпців та типи даних.
3. Перевірте наявність пропущених значень.
4. Досліджуйте розмір даних.

In [29]:
import pandas as pd

df = pd.read_csv('breast_cancer.csv')

print("1. Перші 5 рядків:")
print(df.head())

print("\n2. Інформація про стовпці:")
print(df.info())

print("\n3. Пропущені значення:")
print(df.isnull().sum())

print(f"\n4. Розмір даних: {df.shape}")
print(f"Рядки: {df.shape[0]}, Стовпці: {df.shape[1]}")

print("\n5. Базова статистика:")
print(df.describe())

print("\n6. Розподіл цільової змінної:")
print(df.iloc[:, -1].value_counts())

1. Перші 5 рядків:
                                                                                                                                                                                                        569  \
17.99 10.38 122.80 1001.0 0.11840 0.27760 0.3001 0.14710 0.2419 0.07871 1.0950 0.9053 8.589 153.40 0.006399 0.04904 0.05373 0.01587 0.03003 0.006193 25.38 17.33 184.60 2019.0 0.1622 0.6656 0.7119  0.2654   
20.57 17.77 132.90 1326.0 0.08474 0.07864 0.0869 0.07017 0.1812 0.05667 0.5435 0.7339 3.398 74.08  0.005225 0.01308 0.01860 0.01340 0.01389 0.003532 24.99 23.41 158.80 1956.0 0.1238 0.1866 0.2416  0.1860   
19.69 21.25 130.00 1203.0 0.10960 0.15990 0.1974 0.12790 0.2069 0.05999 0.7456 0.7869 4.585 94.03  0.006150 0.04006 0.03832 0.02058 0.02250 0.004571 23.57 25.53 152.50 1709.0 0.1444 0.4245 0.4504  0.2430   
11.42 20.38 77.58  386.1  0.14250 0.28390 0.2414 0.10520 0.2597 0.09744 0.4956 1.1560 3.445 27.23  0.009110 0.07458 0.05661 0.01867 0.05963 0.009208 14.9

Побудова і налаштування моделей:

1. Розділіть дані на навчальний і тестовий набори.
2. Побудуйте три моделі класифікації (на власний вибір),
наприклад:
1. Логістична регресія.
2. Дерево рішень.
3. Випадковий ліс (Random Forest).
3. Підберіть оптимальні параметри для кожної моделі за допомогою
GridSearchCV (можна вибрати інший оптимізатор).

In [30]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

log_reg = LogisticRegression(random_state=42)
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(random_state=42)

param_grid_lr = {
    'C': [0.1, 1, 10],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}

param_grid_dt = {
    'max_depth': [3, 5, 7, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7, None],
    'min_samples_split': [2, 5]
}

grid_lr = GridSearchCV(log_reg, param_grid_lr, cv=5, scoring='accuracy')
grid_dt = GridSearchCV(dt, param_grid_dt, cv=5, scoring='accuracy')
grid_rf = GridSearchCV(rf, param_grid_rf, cv=5, scoring='accuracy')

grid_lr.fit(X_train_scaled, y_train)
grid_dt.fit(X_train, y_train)
grid_rf.fit(X_train, y_train)

print("Логістична регресія - найкращі параметри:", grid_lr.best_params_)
print("Дерево рішень - найкращі параметри:", grid_dt.best_params_)
print("Випадковий ліс - найкращі параметри:", grid_rf.best_params_)

models = {
    'Logistic Regression': grid_lr.best_estimator_,
    'Decision Tree': grid_dt.best_estimator_,
    'Random Forest': grid_rf.best_estimator_
}

for name, model in models.items():
    if name == 'Logistic Regression':
        y_pred = model.predict(X_test_scaled)
    else:
        y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {accuracy:.4f}")

Логістична регресія - найкращі параметри: {'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}
Дерево рішень - найкращі параметри: {'max_depth': 3, 'min_samples_leaf': 2, 'min_samples_split': 2}
Випадковий ліс - найкращі параметри: {'max_depth': 7, 'min_samples_split': 2, 'n_estimators': 50}
Logistic Regression Accuracy: 0.9298
Decision Tree Accuracy: 0.9211
Random Forest Accuracy: 0.9298


Оцініть моделі. Виведіть точність (accuracy) – обов’язково, матрицю
помилок (confusion matrix) – за вибором та звіт про класифікацію
(classification report) для кожної моделі.

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

for name, model in models.items():
    print(f"\n{name}:")
    print("="*40)

    if name == 'Logistic Regression':
        y_pred = model.predict(X_test_scaled)
    else:
        y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {accuracy:.4f}")

    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(cm)

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))


Logistic Regression:
Accuracy: 0.9298
Confusion Matrix:
[[39  3]
 [ 5 67]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.93      0.91        42
           1       0.96      0.93      0.94        72

    accuracy                           0.93       114
   macro avg       0.92      0.93      0.93       114
weighted avg       0.93      0.93      0.93       114


Decision Tree:
Accuracy: 0.9211
Confusion Matrix:
[[38  4]
 [ 5 67]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.90      0.89        42
           1       0.94      0.93      0.94        72

    accuracy                           0.92       114
   macro avg       0.91      0.92      0.92       114
weighted avg       0.92      0.92      0.92       114


Random Forest:
Accuracy: 0.9298
Confusion Matrix:
[[36  6]
 [ 2 70]]

Classification Report:
              precision    recall  f1-score   support

   

Прогнозування і висновки
1. Оберіть найкращу модель на основі метрик продуктивності.
2. Зробіть прогноз на тестовій вибірці.
3. Виведіть результати прогнозування.

In [33]:
best_model_name = max(models.keys(), key=lambda x: accuracy_score(y_test, models[x].predict(X_test_scaled if x == 'Logistic Regression' else X_test)))
best_model = models[best_model_name]

print(f"Найкраща модель: {best_model_name}")

if best_model_name == 'Logistic Regression':
    y_pred_best = best_model.predict(X_test_scaled)
else:
    y_pred_best = best_model.predict(X_test)

print("\nРезультати прогнозування найкращої моделі:")
results = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred_best
})
print(results.head(10))

print(f"\nТочність найкращої моделі: {accuracy_score(y_test, y_pred_best):.4f}")

Найкраща модель: Logistic Regression

Результати прогнозування найкращої моделі:
   Actual  Predicted
0       0          0
1       1          1
2       0          0
3       1          1
4       0          0
5       1          1
6       1          1
7       0          0
8       0          0
9       0          0

Точність найкращої моделі: 0.9298
