1.Створіть одновимірний масив (вектор) з сумами кожного числа та його
попереднього, починаючи з 1, та виведіть його значення.

In [ ]:
import numpy as np

numbers = np.arange(1, 21)
sums = np.concatenate(([1], numbers[:-1] + numbers[1:]))
print(sums)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
випадкових дійсних чисел від 1 до 10.

In [ ]:
import numpy as np

np.random.seed(42)
matrix = np.random.uniform(1, 10, (3, 3))
print(matrix)

[[4.37086107 9.55642876 7.58794548]
 [6.38792636 2.40416776 2.40395068]
 [1.52275251 8.79558531 6.41003511]]


3.Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
1 до 100 та виведіть мін значення  

In [ ]:
import numpy as np

matrix = np.random.randint(1, 101, (3, 3))
print(matrix)
print(np.min(matrix))

[[78  3  1]
 [ 5 90 14]
 [27  9 79]]
1


4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5.

In [ ]:
import numpy as np

matrix = np.random.rand(4, 4)
print(matrix)
print(np.sum(matrix > 0.5))

[[0.63230583 0.63352971 0.53577468 0.09028977]
 [0.8353025  0.32078006 0.18651851 0.04077514]
 [0.59089294 0.67756436 0.01658783 0.51209306]
 [0.22649578 0.64517279 0.17436643 0.69093774]]
9


5.Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими
числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання
та множення.

In [ ]:
import numpy as np

a = np.random.randint(-10, 11, 4)
b = np.random.randint(-10, 11, 4)
print("Масив a:", a)
print("Масив b:", b)
print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)

Масив a: [ -4   7  -3 -10]
Масив b: [ 0  7 -1 -8]
Додавання: [ -4  14  -4 -18]
Віднімання: [-4  0 -2 -2]
Множення: [ 0 49  3 80]


6.Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 20 та
знайдіть їх добуток.

In [2]:
import numpy as np

matrix_a = np.random.randint(1, 21, size=(3, 3))
matrix_b = np.random.randint(1, 21, size=(3, 3))
result = matrix_a @ matrix_b

print(matrix_a)
print(matrix_b)
print(result)

[[12 17 10]
 [16 15 15]
 [19 12 20]]
[[ 3  5 19]
 [ 7  9  7]
 [18  4 14]]
[[335 253 487]
 [423 275 619]
 [501 283 725]]


7.Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 4 та перемножте їх між собою

In [3]:
import numpy as np

matrix_a = np.random.randint(1, 5, size=(2, 3))
matrix_b = np.random.randint(1, 5, size=(3, 3))
result = matrix_a @ matrix_b

print(matrix_a)
print(matrix_b)
print(result)

[[2 2 1]
 [2 1 2]]
[[4 4 3]
 [4 3 4]
 [1 4 3]]
[[17 18 17]
 [14 19 16]]


8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 7 та знайдіть її обернену матрицю.


In [20]:
import numpy as np

matrix = np.random.randint(1, 8, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix)

print(matrix)
print(inverse_matrix)

[[1 1 3]
 [6 1 4]
 [5 1 3]]
[[-0.25  0.    0.25]
 [ 0.5  -3.    3.5 ]
 [ 0.25  1.   -1.25]]


9.Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні
від 0 до 1 та транспонуйте її.

In [21]:
import numpy as np

matrix = np.random.randint(0, 2, size=(4, 4))
transposed = matrix.T

print(matrix)
print(transposed)

[[0 1 1 0]
 [0 1 0 0]
 [0 1 1 1]
 [0 0 1 1]]
[[0 0 0 0]
 [1 1 1 0]
 [1 0 1 1]
 [0 0 1 1]]


10.Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.

In [22]:
import numpy as np

matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
result = matrix @ vector

print(matrix)
print(vector)
print(result)

[[0.51879062 0.70301896 0.3636296  0.97178208]
 [0.96244729 0.2517823  0.49724851 0.30087831]
 [0.28484049 0.03688695 0.60956433 0.50267902]]
[[0.05147875]
 [0.27864646]
 [0.90826589]
 [0.23956189]]
[[0.78567476]
 [0.64341666]
 [0.69901088]]


11.Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор

In [23]:
import numpy as np

matrix = np.random.rand(2, 3)
vector = np.random.rand(3, 1)
result = matrix @ vector

print(matrix)
print(vector)
print(result)

[[0.14489487 0.48945276 0.98565045]
 [0.24205527 0.67213555 0.76161962]]
[[0.23763754]
 [0.72821635]
 [0.36778313]]
[[0.75336558]
 [0.82709236]]


12.Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть добуток елементів діагоналі другої матриці

In [24]:
import numpy as np

matrix1 = np.random.randint(1, 6, size=(3, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))
diagonal_product = np.prod(np.diag(matrix2))

print(matrix1)
print(matrix2)
print(diagonal_product)

[[4 2 3]
 [1 1 4]
 [3 5 3]]
[[4 4 3]
 [4 3 2]
 [3 3 4]]
48


13.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть різницю їх елементів

In [25]:
import numpy as np

matrix1 = np.random.randint(1, 6, size=(4, 4))
matrix2 = np.random.randint(1, 6, size=(4, 4))
difference = matrix1 - matrix2

print(matrix1)
print(matrix2)
print(difference)

[[4 1 1 2]
 [1 3 4 1]
 [1 2 2 3]
 [4 2 1 4]]
[[4 1 2 1]
 [4 5 5 3]
 [1 1 3 3]
 [3 4 1 4]]
[[ 0  0 -1  1]
 [-3 -2 -1 -2]
 [ 0  1 -1  0]
 [ 1 -2  0  0]]


14.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть найменший елемент матриці.


In [26]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))
min_element = np.min(matrix)

print(matrix)
print(min_element)

[[1 8 4]
 [6 8 4]
 [3 9 3]]
1


15.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить кількість ненульових
елементів в кожному рядку матриці.

In [27]:
import numpy as np

matrix = np.random.uniform(-2, 2, size=(3, 3))
nonzero_counts = np.count_nonzero(matrix, axis=1).reshape(-1, 1)

print(matrix)
print(nonzero_counts)

[[ 1.89465535 -0.8643161  -0.77854456]
 [-0.05754499 -0.20630343  1.97782985]
 [-1.29629899 -1.92769855 -0.02442514]]
[[3]
 [3]
 [3]]
